# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'package'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(9fbf3040-61af-4df0-b41d-4a34667d3240)'
    azureContainerRegistry: '{"loginServer":"azuretcscontainer.azurecr.io", "id" : "/subscriptions/9fbf3040-61af-4df0-b41d-4a34667d3240/resourceGroups/azuretcsteam/providers/Microsoft.ContainerRegistry/registries/azuretcsContainer"}'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Build services'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(9fbf3040-61af-4df0-b41d-4a34667d3240)'
    azureContainerRegistry: '{"loginServer":"azuretcscontainer.azurecr.io", "id" : "/subscriptions/9fbf3040-61af-4df0-b41d-4a34667d3240/resourceGroups/azuretcsteam/providers/Microsoft.ContainerRegistry/registries/azuretcsContainer"}'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Push services'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'AzureConnection'
    Action: 'Stop Azure App Service'
    WebAppName: 'AzureDockerInst'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(9fbf3040-61af-4df0-b41d-4a34667d3240)'
    appType: 'webAppContainer'
    WebAppName: 'AzureDockerInst'
    DockerNamespace: 'azuretcsContainer'
    DockerRepository: 'devopspoc'
    DockerImageTag: 'latest'

- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'AzureConnection'
    Action: 'Start Azure App Service'
    WebAppName: 'AzureDockerInst'